#!/usr/bin/env bash

STATES_FOR='["USA", "JPN", "GBR", "CHN"]'
HAS_STATES_LAYER="$STATES_FOR.indexOf(this.properties.country_code) !== -1"
MIN_AREA=1000000000

command -v npm >/dev/null 2>&1 || {
    echo >&2 "Please install Node.js v6.x!";
    exit 1;
}

command -v mapshaper >/dev/null 2>&1 || {
    echo >&2 "Installing mapshaper!";
    npm i -g mapshaper;
}

mapshaper \
    -i ./ne_10m_admin_1_states_provinces/ne_10m_admin_1_states_provinces.shp snap \
    -simplify weighted 2.2% \
    -o ./states-simplified.json format=geojson force

mapshaper \
    -i \
        ./states-simplified.json \
        ./ne_50m_admin_0_countries/ne_50m_admin_0_countries.shp \
        snap combine-files \
    -rename-layers raw,50m \
    -rename-fields target=raw country_code=adm0_a3,country=admin,state=name,state_code=postal \
    \
    -erase bbox=-172,62.9,-168.5,63.9 \
    -clip bbox=-181,-57,181,87 \
    -each target=raw 'country="French Guiana"; country_code="GUF"' where='country_code==="FRA" && state_code==="CY"' \
    -each target=raw 'country_code="KAZ"' where='country_code==="KAB"' \
    -filter target=raw 'country_code!=="ATA"' \
    -filter target=raw 'type_en!=="Overseas department"' \
    -filter-fields target=raw country,country_code,state,state_code \
    \
    -filter target=raw "$HAS_STATES_LAYER" no-replace name=states \
    -filter-fields target=states country,state,state_code \
    -each target=states "type='state', name=state, has_sublayer=false" \
    \
    -join 50m target=raw keys=country_code,adm0_a3 fields=continent,region_un,subregion \
    -rename-fields target=raw region=region_un,sub_region=subregion \
    -filter target=raw 'region !== null' \
    -filter target=raw 'region.indexOf("Seven") === -1' \
    -dissolve country_code target=raw no-replace copy-fields=country,region,sub_region name=countries \
    \
    -filter-slivers target=countries min-area=1 remove-empty \
    -filter-islands target=countries min-area="$MIN_AREA" remove-empty \
    \
    \
    -each target=countries 'region="North America"' where='sub_region === "Northern America"'  \
    -each target=countries 'region="Central America"' where='sub_region === "Caribbean" || sub_region === "Central America"' \
    -each target=countries 'region="South America"' where='sub_region === "South America"' \
    -dissolve region target=countries no-replace name=regions \
    -each target=regions "type='region', name=region, has_sublayer=true" \
    \
    -filter-fields target=countries country,country_code,region \
    -each target=countries "type='country', name=country, has_sublayer=$HAS_STATES_LAYER" \
    \
    -dissolve target=regions no-replace name=world \
    -each target=world "type='world', name='World', has_sublayer=true" \
    \
    -o ./map.json format=topojson target=world,regions,countries,states bbox force

rm -f ./states-simplified.json
